name: Automation Build and Release

on:
  push:
    branches:
      - buid_yml
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Automation test
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout automation code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create and activate venv
        run: |
          python3.9 -m venv venv
          source venv/bin/activate

      - name: Install frameworks and tools
        run: |
          npm i --location=global appium
          appium driver install uiautomator2
          brew update
          brew install android-platform-tools

      - name: Set up environment variables
        run: |
          echo 'export ANDROID_HOME=~/Library/Android/sdk' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $HOME/.bashrc
          echo 'export PATH=$PATH:/usr/local/lib/android/sdk/platform-tools' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Update Android SDK
        run: source $HOME/.bashrc && $ANDROID_HOME/tools/bin/sdkmanager --update

      - name: Accept Android licenses
        run: yes | source $HOME/.bashrc && $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Checkout application code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: huynhlan21/test
      #     ref: build
      #     path: App

      - name: Download APK file
        run: |
          wget -O application.apk ${{ vars.APK_URL }}
          mkdir -p App
          mv application.apk App/

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Start Appium Server
        run: appium &

      - name: Create AVD and run tests
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            adb devices
            adb install -r App/application.apk
            robot -d Reports --loglevel TRACE UiTests/TestSuite.robot

      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Robot Framework Reports
          path: Reports

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Robot Framework Results
          path: Reports/output.xml

      - name: Stop Appium Server
        run: pkill -f appium

      - name: Clear Appium logs
        run: rm -rf /tmp/appium*

      - name: Delete APK file
        run: rm -f App/application.apk

      - name: Remove virtual environment
        run: |
          rm -rf venv
