name: Automation Build and Release

on:
  push:
    branches:
      - buid_yml
  pull_request:
    branches:
      - master

jobs:
  test:
    name: iOS Automation Test
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Verify Xcode installation
        run: xcodebuild -version -sdk

      - name: Set up iOS simulator
        id: setup-ios-simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: "${{ vars.IOS_DEVICE }}"

      - name: Set device version and UDID as environment variables
        run: |
          echo "Device Info: $(echo '${{ steps.setup-ios-simulator.outputs }}' | jq -c .)"
          echo "IOS_VERSION=${{ steps.setup-ios-simulator.outputs.deviceName }}" >> $GITHUB_ENV
          echo "IOS_UDID=${{ steps.setup-ios-simulator.outputs.udid }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install frameworks and tools
        run: |
          npm i --location=global appium
          appium driver install xcuitest

      - name: Checkout Automation Code
        uses: actions/checkout@v4

      - name: Create and Activate Venv
        run: |
          python3.9 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download and Extract iOS Build
        run: |
          wget -O ios_build.tar.gz ${{ vars.IOS_BUILD_URL }}
          mkdir -p App
          mv ios_build.tar.gz App/
          cd App
          tar -xzf ios_build.tar.gz

      - name: Start Appium Server
        run: appium &

      - name: Run on iOS Simulator
        run: |
          xcrun simctl install "${{ vars.IOS_DEVICE }}" "App/test.app"
          xcrun simctl launch "${{ vars.IOS_DEVICE }}" "${{ vars.IOS_BUNDLE_IDENTIFIER }}"
          appium --platformName "iOS" --deviceName "${{ vars.IOS_DEVICE }}" --udid "${{ env.IOS_UDID }}" --bundleId "${{ vars.IOS_BUNDLE_IDENTIFIER }}" --platformVersion "${{ env.IOS_VERSION }}" --automationName "XCUITest" --app "http://127.0.0.1:4723"
          robot -d Reports --loglevel TRACE UiTests/TestSuite.robot

      - name: Archive Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iOS Automation Reports
          path: Reports

      - name: Stop Appium Server
        run: pkill -f appium

      - name: Clean up
        run: |
          ls {.,App}
          rm -rf /tmp/appium*
          rm -f App/ios_build.tar.gz
          rm -rf App/test.app
          rm -rf venv
